include ./gruvbox_dark.conf

font_size 18.0

enable_audio_bell no

shell zsh

# tab bar settings
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted

# closing confirmation only on non-shell processes
confirm_os_window_close -1

# ctrl+d for exiting shell
map cmd+d send_key ctrl+d

# ctrl+b for tmux shortcuts
map cmd+b send_key ctrl+b

# ctrl+c for copying stuff / interrupting commands
map cmd+c copy_and_clear_or_interrupt

# ctrl+r for vim redo
map cmd+r send_key ctrl+r

# ctrl+{h,j,k,l} for nvim window navigation
map cmd+h send_key ctrl+h
map cmd+j send_key ctrl+j
map cmd+k send_key ctrl+k
map cmd+l send_key ctrl+l

# tab switching
map cmd+page_up previous_tab
map cmd+page_down next_tab

# reload config
map ctrl+shift+r load_config_file

# BEGIN_KITTY_FONTS
font_family      family="Monaspace Xenon"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
