include ./gruvbox_dark.conf
font_size 18.0

# ctrl+d for exiting shell
map cmd+d send_key ctrl+d

# ctrl+b for tmux shortcuts
map cmd+b send_key ctrl+b

# ctrl+c for copying stuff / interrupting commands
map cmd+c copy_and_clear_or_interrupt

# ctrl+r for vim redo
map cmd+r send_key ctrl+r

# tab switching
map cmd+page_up previous_tab
map cmd+page_down next_tab
