[appearance]

[appearance.themes]
system_theme = false
theme = "gruvbox_dark"

[appearance.vertical_tabs]
enabled = false

[appearance.text]
notebook_font_size = 14.0
font_size = 13.0
match_ai_font = true
ai_font_name = "Hack"

[appearance.window]
zoom_level = 125
override_opacity = 100
left_panel_visibility_across_tabs = true

[appearance.input]
input_mode = "pinned_to_bottom"

[appearance.panes]
should_dim_inactive_panes = true

[appearance.tabs]
workspace_decoration_visibility = "always_show"
preserve_active_tab_color = false

[appearance.cursor]
cursor_blink = "enabled"

[code]

[code.editor]
show_code_review_button = false
show_project_explorer = false
show_global_search = false

[warp_drive]
enabled = false

[agents]

[agents.third_party]
should_render_cli_agent_toolbar = true

[agents.warp_agent]
is_any_ai_enabled = false

[agents.warp_agent.other]
show_agent_notifications = false

[system]
prefer_low_power_gpu = false

[text_editing]
vim_mode_enabled = true

[terminal]
osc52_clipboard_access = "deny"
use_audible_bell = false
copy_on_select = true

[terminal.input]
input_box_type_setting = "universal"
honor_ps1 = false
alias_expansion_enabled = true

[notifications]

[notifications.preferences]
is_agent_task_completed_enabled = true
is_long_running_enabled = false
is_needs_attention_enabled = true
is_password_prompt_enabled = true
long_running_threshold = 30
mode = "enabled"
play_notification_sound = true

[warpify]

[warpify.ssh]
ssh_extension_install_mode = "never_install"

[privacy]
telemetry_enabled = false
crash_reporting_enabled = true

[general]
restore_session = true
mouse_scroll_multiplier = 4.0
